import SideNav from "@/components/SideNav";
import UserProvider from "@/providers/userProvider";
import type { Metadata } from "next";
import { Figtree } from "next/font/google";
import "./globals.css";

const font = Figtree({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <UserProvider>
          <SideNav>{children}</SideNav>
        </UserProvider>
      </body>
    </html>
  );
}
